services:
  immich_telegram_uploader:
    image: ghcr.io/nchornii/immich_telegram_uploader
    build: .
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - ./sessions:/app/sessions
      - ./downloads:/app/downloads
